### ISSUE TITLE
您好，不更新了么？

### ISSUE THREAD

**Issue by Focus848** [tiancaiamao/go-internals#18]
您好，非常感谢您的无私奉献，我学习到一些东西。我想请问下，好久没更新内容，是不准备更新了吗？

**Comment by tiancaiamao** [comment]
看情况吧。1.3以后就没有怎么跟Go的源代码了，跟现在的版本还是有一些细节差异的。
短期内暂时是不会更新，但是不排除后面有时间了继续更新。

**Comment by llitfkitfk** [comment]
今天才读到大神的这本书，受教了！
