### ISSUE TITLE
对《10.1 内存模型》的疑问

### ISSUE THREAD

**Issue by nange** [tiancaiamao/go-internals#19]
```golang
package main

import (
  "sync"
  "time"
)

func main() {
  var wg sync.WaitGroup
  var count int
  var ch = make(chan bool, 1)
  for i := 0; i < 10; i++ {
    wg.Add(1)
    go func() {
      ch <- true
      count++
      time.Sleep(time.Millisecond)
      count--
      <-ch
      wg.Done()
    }()
  }
  wg.Wait()
}
```

这段代码文章中说执行go run -race test.go 会检测到数据竞争， 我本地go1.7.3执行并没有检测到竞态。

**Comment by nange** [comment]
看了go内存模型：https://golang.org/ref/mem 
根据happens before关系，上面的代码并不会形成竟态。 
我测试go1.2有竟态，1.3之后的版本都没有，可能是新版本改了规则。

**Comment by tiancaiamao** [comment]
@nange 嗯，是的，这里写的时候Go还是1.1以前的版本
后来应该是修复了。。。太忙了没空更新这边。

关于这个修复，我的看法是Go还是很体贴用户的，后来版本在语言规范里面就添加了相就的规则。
总的来说，以前是要理解这是bug还需要深入理解Go的内存模型...
而修改之后，就符合用户的"直觉"了
