### ISSUE TITLE
10.1 内存模型  happens-before 问题

### ISSUE THREAD

**Issue by unix2dos** [tiancaiamao/go-internals#24]
关于channel的happens-before在Go的内存模型中提到了三种情况：
1.对一个channel的发送操作 happens-before 相应channel的接收操作完成
2.关闭一个channel happens-before 从该Channel接收到最后的返回值0
3.不带缓冲的channel的接收操作 happens-before 相应channel的发送操作完成

>为什么带缓冲的 发送操作 happens-before 相应channel的接收操作完成??
不带缓冲的channel的接收操作 happens-before 相应channel的发送操作完成??

**Comment by tiancaiamao** [comment]
新版本的Go似乎已经没有变化了....
这个是Go1.1左右的版本的情况
具体的可以去查 https://golang.org/ref/mem
